workflows:
  android_apk_release:
    name: 地藏經 APK
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: Accept Android licenses (tolerant)
        script: |
          set -euo pipefail
          export ANDROID_SDK_ROOT="${ANDROID_SDK_ROOT:-/usr/local/share/android-sdk}"
          SDKMANAGER=""
          for p in \
            "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" \
            "$ANDROID_SDK_ROOT/tools/bin/sdkmanager" \
            /usr/local/share/android-sdk/cmdline-tools/latest/bin/sdkmanager \
            /usr/local/share/android-sdk/tools/bin/sdkmanager \
            "$HOME/Library/Android/sdk/cmdline-tools/latest/bin/sdkmanager"
          do
            if [ -x "$p" ]; then SDKMANAGER="$p"; break; fi
          done
          if [ -n "$SDKMANAGER" ]; then
            set +o pipefail
            yes | "$SDKMANAGER" --licenses --sdk_root="$ANDROID_SDK_ROOT" >/dev/null 2>&1 || true
            set -o pipefail
            echo "Android SDK licenses accepted (ignoring harmless SIGPIPE)."
          else
            echo "Warning: sdkmanager not found, skip licenses."
          fi

      - name: Build APK (release)
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
