name: dizangjing_app
description: 地藏經
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  path_provider: ^2.1.5
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

    # ← 新增這些
  sqflite: ^2.3.3+1
  shared_preferences: ^2.2.3
  path: ^1.9.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  sqflite_common_ffi: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/db/

# ← 這個區塊在根層，不是在 dev_dependencies 裡！
flutter_icons:
  android: true
  ios: false
  image_path: assets/icon/app_icon.png


